export const GRUPOS_PRESUPUESTO = {
  'HOGAR Y SERVICIOS':     ['Teléfono', 'Suscripciones'],
  'TRANSPORTE':            ['Tag', 'Ahorro Mantenimiento', 'Ahorro Patente'],
  'SEGUROS':               ['Seguro Banco'],
  'ALE':                   ['Pasajes', 'Comida', 'Fiesta', 'Regalos', 'Transporte', 'Ahorro Viajes Próximos', 'Ahorro Regalos Próximos', 'Otros'],
  'PRÉSTAMOS Y BANCOS':    ['TC Edwards', 'TC BICE', 'Otras Deudas'],
  'AHORROS O INVERSIONES': ['Jubilación S&P 500', 'Fondo Independencia', 'Emergencia'],
  'EMPRENDIMIENTO':        ['Zalantos'],
  'CUIDADO PERSONAL':      ['Corte de Pelo', 'Ropa'],
  'ENTRETENIMIENTO':       ['Carrete', 'Padel', 'Uber', 'Regalos'],
  'COMIDA':                ['Alimentos', 'Restaurantes', 'Otros'],
  'VIAJES':                ['Pasajes', 'Comida', 'Alojamiento', 'Otros'],
  'SALUD':                 ['Consulta Médica', 'Remedios', 'Suplementos', 'Otros'],
}

export const COLOR_GRUPO = {
  'HOGAR Y SERVICIOS':     '#a3e635',
  'TRANSPORTE':            '#fbbf24',
  'SEGUROS':               '#94a3b8',
  'ALE':                   '#f472b6',
  'PRÉSTAMOS Y BANCOS':    '#fb7185',
  'AHORROS O INVERSIONES': '#34d399',
  'EMPRENDIMIENTO':        '#a78bfa',
  'CUIDADO PERSONAL':      '#c084fc',
  'ENTRETENIMIENTO':       '#38bdf8',
  'COMIDA':                '#fb923c',
  'VIAJES':                '#818cf8',
  'SALUD':                 '#4ade80',
}

export const TODOS_LOS_TIPOS = [
  'A medias',
  'Ajuste',
  'Auto',
  'Comida',
  'Deporte',
  'Deuda',
  'Externo',
  'Mantención',
  'Ocio',
  'Otro',
  'Proyecto',
  'Regalo',
  'Regalo propio',
  'Ropa',
  'Salud',
  'Suscripcion',
  'Transporte',
  'Turno',
  'Unknown',
  'VA',
  'Viaje',
]

export const BANCOS = ['Edwards', 'BICE', 'TC Papa', 'Otro']

export const COLOR_CATEGORIA = {
  Ocio: '#38bdf8',
  Viaje: '#818cf8',
  Comida: '#fb923c',
  Externo: '#a78bfa',
  Salud: '#34d399',
  Regalo: '#f472b6',
  Transporte: '#fbbf24',
  Deporte: '#4ade80',
  Ajuste: '#94a3b8',
  Turno: '#6366f1',
  Otro: '#64748b',
  Mantención: '#f87171',
  Ropa: '#c084fc',
  Deuda: '#fb7185',
  'A medias': '#38bdf8',
  Proyecto: '#22d3ee',
  'Regalo propio': '#f9a8d4',
  Suscripcion: '#a3e635',
  Unknown: '#475569',
  VA: '#7dd3fc',
  Auto: '#fcd34d',
}
